"""fixed id type mismatch

Revision ID: 52258d8961d3
Revises: b4a2553a088c
Create Date: 2025-03-10 19:30:13.000963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52258d8961d3'
down_revision = 'b4a2553a088c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('encrypted_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
